In [1]:
table_dir = '~/LLM_VQA_MultiPanel/figure_notebooks/'

table_file = 'other_datasets_chart_asLatex.txt'

In [3]:
from astropy.table import Table
import os

table_dir = os.path.expanduser(table_dir)

In [14]:

# Read a .tex file or a string containing the table
dat = Table.read(table_dir+table_file, format='ascii.latex')

# Convert to Pandas DataFrame
df = dat.to_pandas()

In [15]:
!ls ~/LLM_VQA_MultiPanel/figure_notebooks/*asLa*

/Users/jnaiman/LLM_VQA_MultiPanel/figure_notebooks/other_datasets_chart_asLatex.txt

In [17]:
df.head()

,Name,Date,Line,Bar,Sctr,Pie,Hist,Othr,BB,Data Link,MultiPanel,Citation(s)
0,FigureQA,2018,$\checkmark$,$\checkmark$,--,$\checkmark$,--,--,$\checkmark$,--,--,\cite{kahou_figureqa_2018}
1,ChartLlama,2023,--,--,$\checkmark$,--,--,$\checkmark$,--,--,--,\cite{han_chartllama_2023}
2,ChartAssistant/SFT,2024,$\checkmark$,$\checkmark$,$\checkmark$,$\checkmark$,--,$\checkmark$,--,P,--,\cite{meng_chartassistant_2024}
3,MMCA,2024,$\checkmark$,$\checkmark$,$\checkmark$,$\checkmark$,$\checkmark$,$\checkmark$,--,--,--,\cite{liu_mmc_2024}
4,Chart2Text/to-text,2020/22,$\checkmark$,$\checkmark$,$\checkmark$,$\checkmark$,--,$\checkmark$,P,$\checkmark$,--,"\cite{kantharaj_chart--text_2022,obeid_chart--..."

In [21]:
# new table based on if table
chart_types = []
for i,r in df.iterrows():
    ct = ''
    for cn,tag in zip(['Line', 'Bar', 'Sctr', 'Pie', 'Hist', 'Othr'], ['l','b','s','p','h','o']):
        if 'checkmark' in r[cn]:
            ct += tag +','
    ct = ct.removesuffix(',')
    chart_types.append(ct)

In [25]:
df_table = df.copy()[['Name', 'Date', 'BB', 'Data Link', 'MultiPanel', 'Citation(s)']]
df_table['Plot Type'] = chart_types
# reorder
df_table = df_table[['Name', 'Date', 'Plot Type', 'BB', 'Data Link', 'MultiPanel', 'Citation(s)']]

In [26]:
df_table.head()

,Name,Date,Plot Type,BB,Data Link,MultiPanel,Citation(s)
0,FigureQA,2018,"l,b,p",$\checkmark$,--,--,\cite{kahou_figureqa_2018}
1,ChartLlama,2023,"s,o",--,--,--,\cite{han_chartllama_2023}
2,ChartAssistant/SFT,2024,"l,b,s,p,o",--,P,--,\cite{meng_chartassistant_2024}
3,MMCA,2024,"l,b,s,p,h,o",--,--,--,\cite{liu_mmc_2024}
4,Chart2Text/to-text,2020/22,"l,b,s,p,o",P,$\checkmark$,--,"\cite{kantharaj_chart--text_2022,obeid_chart--..."